### PR TITLE
Configurable schema name

### PR DESCRIPTION
**Pull request by mgwidmann**
The migration is largely in control of the user and so I thought it'd be nice to allow changing of the schema name.

### CODE REVIEW

**Comment by joeellis** [comment]
+1.  I generally prefer to keep my entity (model / controller / table / whatever) names separate from the actual libraries I use to control them

**Comment by mgwidmann** [comment]
I figured if @hassox  is ok with this, I may submit a similar PR to allow the column names to change, though unsure how necessary that is.

**Comment by joeellis** [comment]
@mgwidmann Ah, yeah that might be unnecessary.  I can't think of a good reason why someone would want to change them...

**Comment by mgwidmann** [comment]
yeah maybe this is all thats necessary

**Pull request merged**
