### PR TITLE
Ecto 2.0

### PR DESCRIPTION
**Pull request by talklittle**
ref GH-16

### CODE REVIEW

**Comment by hassox** [comment]
Thanks @talklittle! I think we should probably bump the version a fair bit for this one.

**Comment by talklittle** [comment]
@hassox Agreed. Let me know if you want me to make any changes. Thanks.

Also are you thinking to merge after Ecto 2.0.0 final, or would you be willing to merge the 2.0.0-RC dependency?

**Comment by hassox** [comment]
Hmm. I'm not sure how to release this for ecto 2 so that it doesn't break folks that aren't using it yet. Any ideas?

**Comment by talklittle** [comment]
@hassox I was thinking it's safe to bump guardian_db version to 0.6.0, since Hex dependencies on `~> 0.5.0` won't be affected. They'll just need to update Ecto before they can use any newer guardian_db releases.

Note that `~> 0.5` is affected since it expands to `>= 0.5.0 and < 1.0.0`, but `~> 0.5.0` expands to `>= 0.5.0 and < 0.6.0`. Maybe adding a note in the guardian_db README will be sufficient? I personally wasn't aware of this until just now. http://elixir-lang.org/docs/stable/elixir/Version.html

AFAIK Ecto 2 should be an eventual migration for all downstream projects. I'm not aware of any reasons to keep libraries compatible with Ecto 1 in the future.

**Comment by ashrafhasson** [comment]
why not have a note in the CHANGELOG prefixing (Breaking) to the item being updated.
:+1: on moving to Ecto 2.0, I have dependency conflicts calling for Ecto 2.0 actually :D

**Comment by doomspork** [comment]
@hassox could we release this as `0.6.0` and back port applicable fixes to `0.5.x`?  Anyone staying on Ecto 1 can stick to `~> 0.5` in their mix.exs.

**Comment by hassox** [comment]
@doomspork that sounds like a decent plan.

**Pull request merged**
