### PR TITLE
Elixir 1.4

### PR DESCRIPTION
**Pull request by manukall**
this fixes elixir 1.4 warnings, but it's already based on my other PR that fixes warnings for Ecto 2.1.

if the other PR is not going to be merged, let me know and i'll fix the 1.4 warnings in master.

### CODE REVIEW

**Comment by doomspork** [comment]
@manukall could you resolve the conflicts?

**Comment by doomspork** [comment]
Howdy @manukall, any chance you could rebase your branch?

**Comment by manukall** [comment]
@doomspork sure. i somehow missed that last comment. hope i'll get to it this evening.

**Comment by manukall** [comment]
@doomspork there you go

**Comment by doomspork** [comment]
Thank you @manukall!!

**Pull request merged**
