### PR TITLE
change dependency of postgrex to ">= 0.11.1 and < 0.14.0"

### PR DESCRIPTION
**Pull request by blisscs**
Sorry for the previous pull requests. 
When I used the previous pull request one I wouldn't get it to compile later on. 
And I further checked also that the postgrex 0.14-dev is also started, so to be save I put it >= 0.11.0 and <0.14.0.

Thank you for making this library.
blisscs

### CODE REVIEW

**Comment by doomspork** [comment]
Thank you @blisscs!  You'll need to rebase your PR on the recent changes.  I'll go ahead and pull this change down today or tomorrow just to confirm it's working 👍

**Comment by yordis** [comment]
@doomspork I think we do not need anymore

**Comment by doomspork** [comment]
Thank you for being on top of this @yordis!  Could you tell @blisscs what he'll need to get this to working with his project?

**Comment by yordis** [comment]
@doomspork he wants to download `0.14.0` which is not on `Hex.pm` so everything depends of what do you want to do.

I do not recommend to add `0.14.0` as a supported version because we do not know if it will fail or not. Right now it will include patches from `~> 0.13` but not `0.14` because there is not release yet on `hex.pm`

@blisscs I would recommend to add `postgrex` is some other app and use `override: true` on the dependency declaration for force  your applications to use `0.14` if you want

**Comment by blisscs** [comment]
Thank you @yordis 
Actually the purpose of putting < 0.14, cause I thougt it is the same of ~> 0.13.
As previously I created pull request of only postgrex >= 0.13, since I didn't check every well that it wasn't compiling. So I switch >= 0.11.0 and ~> 0.13 and it's working. and I also check that there is already a development started on the 0.14-dev on the postgrex mix file. So I somehow write <= 0.11.0 and < 0.14.0. 
My apology creating this issue.

**Pull request closed without merging**
