### PR TITLE
Add Travis for Elixir 1.6 and OTP 21

### PR DESCRIPTION
**Pull request by samhamilton**
Small addition supporting Elixir 1.6 and OTP 21 tests

### CODE REVIEW

**Comment by yordis** [comment]
@samhamilton would you mind to use this setup https://github.com/ueberauth/guardian/blob/master/.travis.yml ?

You can follow this commit https://github.com/ueberauth/guardian/commit/bed4961922054198404a3b7fd9f8c6dd79530cfc which forget about some code changes related to the formatter.

And add  OTP 21 as well for sure.

Let me know because I thought I did this but I guess I forgot about it. Anyway thank you a lot for your contribution, appreciated!

**Comment by doomspork** [comment]
Ping @samhamilton any chance you want to update the file to @yordis' suggestion?  If not we can close and open a new PR.

**Comment by nathany** [comment]
@doomspork I apologize for my poor online communication skills and the misunderstanding that resulted on #94. 

I spent an afternoon working on that pull request to the best of my ability (I am new to Elixir, but had a lot of help from many people). It even incorporated the TravisCI changes requested here by comparing to [your other travis file](https://github.com/ueberauth/guardian/blob/master/.travis.yml). 

Thank you for providing this library and supporting it. I'll try to do better in future open source interactions -- in what I say and don't say. Take care.

**Comment by samhamilton** [comment]
@doomspork sorry - work is overflowing, will submit a new PR when i have some free moments

**Comment by nathany** [comment]
Thanks @samhamilton. 

@yordis made some updates in #95.

**Pull request closed without merging**
